In [14]:
import numpy as np
import random
arr= np.random.randint(low=1 , high = 50 ,size=(2,2))
print(arr)

[[ 3 35]
 [21 16]]


In [15]:
list1=[2,3,45,2,1]
array1=np.array(list1)
print(array1)

[ 2  3 45  2  1]


## 2D

In [17]:
list2=[[1,2,3],[4,5,6]]
array2=np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


### 3D

In [19]:
list3=[[1,2,3],[4,5,6],[7,8,9]]
array3=np.array(list3)
print(array3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
array3.shape

(3, 3)

In [21]:
array3[0][2]

3

In [22]:
array3.ndim

2

In [24]:
random_array=np.random.randint(low=2,high=20,size=(2,3,4))
print(random_array)


[[[15  4  3 16]
  [15  8 14  8]
  [15  8  3  4]]

 [[ 2  7 13 15]
  [ 9  7 12  8]
  [ 4 19  8 18]]]


In [27]:
random_array[1,2,2]

8

In [29]:
random_array[-1,1,1]

7

In [31]:
random_array[-1,-1,1]

19

## Slicing Numpy array

## 1D

In [34]:
random_array[1:1]

array([], shape=(0, 3, 4), dtype=int32)

In [6]:
import numpy as np
list4 = [[1,2,3,4,5],[4,5,6,7,8]]
slicing_list=np.array(list4)
print(slicing_list)

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [8]:
slicing_list[1,2:4]

array([6, 7])

In [9]:
slicing_list.shape

(2, 5)

In [11]:
slicing_list[1:,1:4]

array([[5, 6, 7]])

## 3D

In [13]:
random_arr=np.random.randint(low=10, high=50, size=(4,3,4))
print(random_arr)

[[[17 17 19 19]
  [26 47 41 38]
  [27 31 47 21]]

 [[27 10 27 16]
  [13 42 20 40]
  [27 36 29 47]]

 [[14 32 49 44]
  [39 29 13 39]
  [14 24 20 47]]

 [[36 28 18 32]
  [10 18 39 24]
  [33 25 41 15]]]


In [30]:
slicing_arr=np.array(random_arr).type
slicing_arr[-2:,:2,-2::]

AttributeError: 'numpy.ndarray' object has no attribute 'type'